#!/bin/zsh

show_help() {
echo "

  colnum:	Numbers the columns of a csv file for easy reference

  Usage: colnum [-s] [-d sep] filename

  -s            Show data sample [default no]
  -d            Field delimiter [default ^]
  -h            Show this help
  filename      File to list columns. Required

  Examples:     colnum somefile.csv
                colnum -s somefile.csv
                colnum -d '|' somefile.csv
                colnum -sd '#' somefile.csv

"
}


sep="^"
ex=0

# The first : is to avoid printing errors at reading parameters
while getopts ":es:h" opt; do
  case $opt in
    s)
      ex=1;;
    d)
      sep=$OPTARG;;
    h)
      show_help
      exit 0;;
    \?)
      echo "Invalid option: -$OPTARG." >&2
      show_help
      exit 2;;
  esac
done

#This tells getopts to move on to the next argument.
shift $(($OPTIND-1))

if [ -z "$1" ]; then
  echo "Error, you must specify a filename."
  show_help
  exit 1
fi

nl=$(wc -l "$1")

awk -F"$sep" -v awk_ex=$ex -v awk_nl=$nl '
  BEGIN{
    split("", body)
    srand()
    # Random line between 2nd and last lines of the file
    rnd_line=int(rand() * (awk_nl - 1) + 2)
  }
  {
    if (FNR==1) {
      split($0, header)
      if (awk_ex==0) {
        exit 0
     }
    }
    if (FNR==rnd_line && awk_ex) {
      split($0, body)
      exit 0
    }
  }
  END {
    for (i in header) {
      resto = (length(body) > 0) ? " -> " body[i] : ""
      print i ". " header[i] resto
    }
 }' "$1"
